.TH rdesktop 1 "October 2002"
.SH NAME
.I rdesktop
\- Remote Desktop Protocol client
.SH SYNOPSIS
.B rdesktop [options] server[:port]
.br
.SH DESCRIPTION
.I rdesktop
is a client for Microsoft Windows NT Terminal Server, Windows 2000 Terminal
Services, Windows XP Remote Desktop, and possibly other Terminal Services
products.  rdesktop currently implements the RDP version 4 protocol.

.SH OPTIONS
.TP
.BR "-u <username>"
Username for authentication on the terminal server.
.TP
.BR "-d <domain>"
Domain for authentication.
.TP
.BR "-s <shell>"
Startup shell for the user - starts a specific application instead of Explorer.
.TP
.BR "-c <directory>"
The initial working directory for the user.  Often used in combination with -s
to set up a fixed login environment.
.TP
.BR "-p <password>"
The password to authenticate with.  Note that this may have no effect if
"Always prompt for password" is enabled on the server.  WARNING: if you specify
a password on the command line it may be visible to other users when they use
tools like ps.  Use -p - to make rdesktop request a password at startup (from
standard input).
.TP
.BR "-n <hostname>"
Client hostname.  Normally rdesktop automatically obtains the hostname of the
client.
.TP
.BR "-k <layout>"
Keyboard layout to emulate.  This requires a corresponding keymap file to be
installed.  The standard keymaps provided with rdesktop follow the RFC1766
naming scheme: a language code followed by a country code if necessary - e.g.
en-us, en-gb, de, fr, sv, etc.  The default is en-us (a US keyboard).
.TP
.BR "-g <geometry>"
Desktop geometry (WxH). If geometry is the special word "workarea", the geometry
will be fetched from the extended window manager hints property _NET_WORKAREA, from
the root window. 
.TP
.BR "-f"
Enable fullscreen mode.  This overrides the window manager and causes the
rdesktop window to fully cover the current screen.  Fullscreen mode can be
toggled at any time using Ctrl-Alt-Enter.
.TP
.BR "-b"
Force the server to send screen updates as bitmaps rather than using
higher-level drawing operations.
.TP
.BR "-e"
Disable encryption.  This option is only needed (and will only work) if you
have a French version of NT TSE.
.TP
.BR "-m"
Do not send mouse motion events.  This saves bandwidth, although some Windows
applications may rely on receiving mouse motion.
.TP
.BR "-C"
Use private colourmap.  This will improve colour accuracy on an 8-bit display,
but rdesktop will appear in false colour when not focused.
.TP
.BR "-K"
Do not override window manager key bindings.  By default rdesktop attempts
to grab all keyboard input when it is in focus.
.TP
.BR "-T <title>"
Window title.
.TP
.BR "-D"
Hide window manager decorations, by using MWM hints. 

.PP
.SH LINKS
Main website of rdesktop
.br
\fIhttp://www.rdesktop.org/
.LP
.PP
